flaskApp:
  image: rugant/flask-app
  tag: "latest"              # Jenkins will override this
  replicaCount: 2
  service:
    type: NodePort
    port: 80
    nodePort: 30080

postgres:
  image: postgres:14
  db: testdb
  user: testuser
  password: testpass
  storage: 1Gi