apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  selector:
    app: flask-app
  type: {{ .Values.flaskApp.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.flaskApp.service.port }}
      targetPort: 5000
      nodePort: {{ .Values.flaskApp.service.nodePort }}
